Add initial support for git worktrees
Signed-off-by: Tomas Cohen Arazi <tomascohen@theke.io>

diff --git a/bin/ktd b/bin/ktd
--- a/bin/ktd
+++ b/bin/ktd
@@ -300,6 +300,12 @@ else
         if [ -d "$KTD_HOME" ]; then
             # All good :-D
 
+            if [ ! -d "${SYNC_REPO}" ]; then
+                printf "\nThe mandatory \$SYNC_REPO variable points to an invalid directory.\nIt needs to point to a Koha clone directory.\n\n"
+                usage
+                exit 1
+            fi
+
             # tweak used images
             set_image
 
@@ -328,6 +334,14 @@ else
 
             if [ "$ENABLE_SSO" != "no" ]; then
                 COMPOSE_OPTIONS="${COMPOSE_OPTIONS} -f docker-compose.sso.yml"
+            fi
+
+            # worktree?
+            if [ ! -d "${SYNC_REPO}/.git" ]; then
+                GIT_WORKTREE_SOURCE=$(cat ${SYNC_REPO}/.git | cut -d" " -f2)
+                export GIT_WORKTREE_SOURCE="${GIT_WORKTREE_SOURCE%%/.git/worktrees/*}"
+                printf "\nDetected Git worktree. Mounting ${GIT_WORKTREE_SOURCE}.\n\n"
+                COMPOSE_OPTIONS="${COMPOSE_OPTIONS} -f compose/worktree.yml"
             fi
 
             export KOHA_ELASTICSEARCH="${KOHA_ELASTICSEARCH}"
